### ISSUE TITLE
Improve overall code

### ISSUE THREAD

**Issue by Seekherr** [ElementalMinecraftGaming/JericoSystemisation#2]
Divide code into seperate classes, and use one class per file, the file name should be the class name. Seperate these files into diectories with informative names. Messy code is never fun to look at.
Also, please don't execute MySQL queries on the Main Thread, they're very experience, even if you make use of connection pooling and stuff, use libasynql. You COULD probably get away using a seperate thread or an AsyncTask. Also, use better property names and make sure to type them as much as you can. I haven't looked into the code much, but yeah you should work on these if you're actually going to maintain the plugin.

**Comment by Seekherr** [comment]
My bad lol you're using SQLITE3*, but at least I got the SQL right!

**Comment by ElementalMinecraftGaming** [comment]
This isn't a requirement or needed, the plugin can be maintained easily just fine.
This code was also made to run not read, as long as the reviewers can read it then it is good enough for me. 😂

**Comment by Seekherr** [comment]
> This isn't a requirement or needed, the plugin can be maintained easily just fine.
> This code was also made to run not read, as long as the reviewers can read it then it is good enough for me. 😂 

Well that's just lazy programming then, but I understand, you aren't getting paid, well maybe add a 'Not recommended for production use' warning.
